version: '3'
services:
  elasticsearch1:
    build: .
    image: vertexium/elasticsearch7
    ports:
      - "9200:9200"
      - "9300:9300"
    hostname: elasticsearch1
    container_name: elasticsearch1
    environment:
      - "discovery.type=single-node"
    #  - "discovery.zen.ping.unicast.hosts=elasticsearch1,elasticsearch2,elasticsearch3"
  cerebro:
    image: lmenezes/cerebro
    ports:
      - "9000:9000"
    hostname: cerebro
    container_name: cerebro
